// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4t9DiTa8Ep7c77l_E2BHAU-5f8q4vLqA',
    appId: '1:118029874724:web:c335c4f038457ae99ecab1',
    messagingSenderId: '118029874724',
    projectId: 'inklink-4d2da',
    authDomain: 'inklink-4d2da.firebaseapp.com',
    storageBucket: 'inklink-4d2da.firebasestorage.app',
    measurementId: 'G-TTV83QH560',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3f0wScoQHZfmkHqWJRPMtZFYBXz-kzEc',
    appId: '1:118029874724:ios:3566fc445d58f9339ecab1',
    messagingSenderId: '118029874724',
    projectId: 'inklink-4d2da',
    storageBucket: 'inklink-4d2da.firebasestorage.app',
    iosBundleId: 'com.example.inklink',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpdKfYv5ak2h900jRJi6YZxai_hxL8KqQ',
    appId: '1:118029874724:android:4fe8a56d2ed30af59ecab1',
    messagingSenderId: '118029874724',
    projectId: 'inklink-4d2da',
    storageBucket: 'inklink-4d2da.firebasestorage.app',
  );

}